### ISSUE TITLE
There is something wrong with the Client IP page

### ISSUE THREAD

**Issue by RCMainak** [wwphp-fb/wwphp-fb.github.io#27]
Hey, I guess I noticed few mistakes in the [`How to get client's IP address in PHP?`](https://wwphp-fb.github.io/faq/how-to-get-clientsip-in-php/) article. Please refer to the attached image below.

![bug image](https://lh3.googleusercontent.com/AUQTAoxfCph0lVlBE3VKG2pY2PLIpRD96i03ENzmSKcTLJrNpNiUzMQanofoupRoPXiZjJxf=w1555-h833)

**Comment by nhlm** [comment]
I don't see an image O_o

**Comment by mike-bailey** [comment]
@nhlm Presumably because AWS S3 us-east-1 is offline. Github uses it.

**Comment by petk** [comment]
Thanks for the report @RCMainak :+1:

AWS S3 is having temporary issues with images not being displayed at some locations as mentioned by @mike-bailey

First part of typo fixed via 910d4e2c4e5e60afb1a113c076edf6a8abf60832

Probably some better explanation and code example coming up as well.

**Comment by RCMainak** [comment]
@petk thank for attaching the image. Your patch doesn't fix all the bugs. There is one remaining in the `else {}` clause. 

Looking forward to the improved version as well :+1:

**Comment by petk** [comment]
@RCMainak the final ip assignment is meant for using the usual expected $_SERVER['REMOTE_ADDRESS'] but sometimes this might not be set so it defaults to `0.0.0.0`. The "double question mark" operator is so-called [null coalescing operator](http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce).

A code example is probably too simple for real usage. Best would be to use the [Symfony HttpFoundation](https://github.com/symfony/http-foundation/blob/master/Request.php#L798)) component or [Zend Http Component](https://github.com/zendframework/zend-http/blob/master/src/PhpEnvironment/RemoteAddress.php)

Let me check...

**Comment by RCMainak** [comment]
Okay, I see. That thing is a PHP 7 thing. I must admit it's a nice little addition. Thank you for informing me :smile:

**Comment by petk** [comment]
The example has now also a minor disclaimer and some additional information has been added to understand the non-standard headers more:
https://wwphp-fb.github.io/faq/how-to-get-clientsip-in-php/

In case there are more issues, we can explain this in more details later on. Thanks for reporting issues.

Closing.
